project:
  type: website

website:
  title: "cacostakis.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    toc: true

editor: visual

